# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hyde Sass
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Tweaked by <a href="https://twitter.com/benkalsky" target="_blank">@benkalsky</a>.'
url:              http://benkalsky.net/hyde-sass
baseurl:          ''

sass:
  style: :expanded

author:
  name:           'Ben Kalsky'
  url:            https://twitter.com/benkalsky

paginate:         5

# Custom vars
version:          2.1.1

github:
  repo:           https://github.com/benkalsky/hyde-sass

gems:
  - jekyll-paginate
  - jekyll-gist
